# Generated by Django 3.1.5 on 2021-10-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signup_App', '0002_registration_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user_type',
        ),
        migrations.AddField(
            model_name='registration',
            name='doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='patient',
            field=models.BooleanField(default=False),
        ),
    ]
