# Generated by Django 3.1.5 on 2021-10-11 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Signup_App', '0002_registration_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='address',
        ),
    ]
