# Generated by Django 3.1.5 on 2021-10-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signup_App', '0003_auto_20211010_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='patient',
        ),
        migrations.AddField(
            model_name='registration',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Patient', 'Patient')], max_length=20, null=True),
        ),
    ]
