# Generated by Django 3.1.5 on 2021-10-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Signup_App', '0004_auto_20211010_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user_type',
        ),
    ]
