# Generated by Django 3.1.5 on 2021-10-10 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Signup_App', '0005_remove_registration_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('Age', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], null=True)),
                ('Gender', models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=20, null=True)),
                ('State', models.CharField(max_length=20, null=True)),
                ('District', models.CharField(max_length=20, null=True)),
                ('PIN_code', models.IntegerField(null=True)),
                ('Address', models.CharField(max_length=200)),
                ('Mobile_no', models.IntegerField(null=True)),
            ],
        ),
    ]
