# Generated by Django 3.1.5 on 2021-10-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Signup_App', '0006_userdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='Gender',
            new_name='user_type',
        ),
    ]
